### ISSUE TITLE
create a SLACK group chat

### ISSUE THREAD

**Issue by daitanfutekina** [daitanfutekina/minigamehub#1]
if you click on codechicaplusplus it shows the names of everyone in this class
the people are:
liam, kelly, gabby, and Allaah.

**Comment by superrrk** [comment]
Hello team, the slack group chat should already be created with everyone in it. Please say hello in the group chat to make sure we are all in there. If there are any issues, let me know!

**Comment by daitanfutekina** [comment]
> Hello team, the slack group chat should already be created with everyone in it. Please say hello in the group chat to make sure we are all in there. If there are any issues, let me know!

i don't see it, can you send in a test message first? (some group chat systems work like that)
